<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="VijayKanth" failures="2" tests="2" name="Default test(failed)" time="0.129" errors="0" timestamp="2022-09-22T12:38:44 IST">
  <testcase classname="testngrealted.TestNgRetryFailedDemo" name="test3" time="0.039">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testngrealted.TestNgRetryFailedDemo.test3(TestNgRetryFailedDemo.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="testngrealted.TestNgRetryFailedDemo" name="test2" time="0.002">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at testngrealted.TestNgRetryFailedDemo.test2(TestNgRetryFailedDemo.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="testngrealted.TestNgRetryFailedDemo" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
